### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by dutykh** [erichlf/Thesis#1]
Dear Erich,

And why don't you add the final PDF file of your thesis to this repository? :)

It would be very helpful who want to read it without compiling everything from scratch...

Best wishes,
Denys

**Comment by erichlf** [comment]
I realized I was, in fact, missing three files also. In the end I included the PDF in the repo.

**Comment by dutykh** [comment]
Thanks a lot, Erich! And good luck in Lausanne! :)
